# Generated by Django 2.1.3 on 2018-11-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domstoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nafn')),
                ('url', models.CharField(max_length=255, verbose_name='slóð')),
            ],
            options={
                'verbose_name': 'Dómstóll',
                'verbose_name_plural': 'Dómstólar',
            },
        ),
        migrations.CreateModel(
            name='Domur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
                ('domstoll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domar.Domstoll', verbose_name='dómstóll')),
            ],
        ),
    ]
