# Generated by Django 2.1.3 on 2018-11-22 10:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('domar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domur',
            options={'verbose_name': 'Dómur', 'verbose_name_plural': 'Dómar'},
        ),
        migrations.AddField(
            model_name='domur',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='domur',
            name='appellants',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domur',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domur',
            name='parties',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domur',
            name='plaintiffs',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domur',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='domur',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
