# Generated by Django 2.1.3 on 2018-11-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domar', '0003_auto_20181122_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='domur',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
