# Generated by Django 2.1.3 on 2018-11-28 10:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domar', '0006_domur_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domur',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
