# Generated by Django 2.1.4 on 2018-12-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domar', '0008_domur_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='domstoll',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
